### ISSUE TITLE
list of regions to iterate through

### ISSUE THREAD

**Issue by brentp** [brentp/jigv#1]
given a VCF or BED, desktop IGV can iterate through variants/regions with `ctrl+f`. AFAICT, that's not available in igv.js. But we could generate a list of links to click through.

**Comment by brentp** [comment]
this is partly implemented as of v0.0.4, should update to support BED files as well.

**Comment by jrobinso** [comment]
Hi all.  First great work @brentp.  I could probably add a ctrl-f function,  would need a way to select a track.   However a list of loci you click external to igv.js you might be a better solution.

For another approach check out github.com/igvteam/igv-reports.   It was developed mostly for this use case.   This is a python script that walks through a list of variant/regions, extracts all the data needed,  packs it into the webpage as a blob, and generates a table to skip through.   Some, all, or none of that might be useful in this case just pointing it out.   There is an example or two in the project.

**Comment by brentp** [comment]
@jrobinso thanks for having a look (and for making igv.js) I just have it default to iterate over the first vcf track which is sufficient for at least my needs (and i couldn't figure out how to select a track). it has to make a call to the server, but that seems reasonable given the setup.
