### ISSUE TITLE
Read sequence is "*"

### ISSUE THREAD

**Issue by hdashnow** [brentp/jigv#10]
right click on read -> View read sequence sometimes results in:

![Screen Shot 2020-04-09 at 2 23 58 PM](https://user-images.githubusercontent.com/3794821/78937495-e168ff00-7a6d-11ea-81f4-4fa415d3ac6b.png)

One occurs on some reads, while others are fine. Can PM you the file if that's helpful.

**Comment by brentp** [comment]
this must be from igv.js I don't mess with that in jigv. if you make a file with a single alignment (pair) that shows the problem, I can verify that is the case.
