### ISSUE TITLE
Anotation track

### ISSUE THREAD

**Issue by wojciech-galan** [brentp/jigv#12]
Is it possible to view the annotation track in the current `jigv` version? How to do this?

**Comment by brentp** [comment]
hi, what type of annotation track are you trying to show? if you send a bed file it will show it.

**Comment by wojciech-galan** [comment]
I'd like to show a track containing RefSeq Genes. They are visible by default in IGV.

**Comment by brentp** [comment]
the refseq genes is displayed by default, you don't need the bed file. perhaps you just didn't see it before you added the other bed file?

**Comment by wojciech-galan** [comment]
Yes, you are right. The window size and track display modes didn't fit. I fixed it injecting java script: `--js "for (i = 0; i < 2; i++) {options.tracks[i].autoHeight = true } "`
Thank you for your help!
