### ISSUE TITLE
can this tools generate a file contains each variant of RF and FR number of base A T C G N

### ISSUE THREAD

**Issue by asmlgkj** [brentp/jigv#16]
can this tool get the data to a plain file? thanks a lot
![image](https://user-images.githubusercontent.com/50854682/134372998-78445d30-b6e8-4680-8474-27e1dcfa5078.png)

**Comment by brentp** [comment]
No, that's calculated by igv.js on the fly. So it will show in the jigv plot but it's not readily availble to write to text. you can use a pileup tool or a variant caller at specific loci to extract allele depths for given sites.

**Comment by asmlgkj** [comment]
yes, pysam can do such work, but not that fast, because mosdepth is so fast, so I wonder if you prepare to add this function into jigv
