### ISSUE TITLE
jigv settings for targeted deep sequencing

### ISSUE THREAD

**Issue by shukwong** [brentp/jigv#19]
would love to use jigv for manually checking the targeted deep sequencing variants. It seems that when it gets over 1500X there is some sampling of reads going on. It is not obvious where to modify the code to ask jigv to not subsample the reads.

**Comment by brentp** [comment]
Hi Wendy, I don't think jigv is the cause. It's been a while since I've looked at this code but I just went through it and don't see any subsampling in the JS or the nim. 
I also don't see any mention about 1500 in the igv.js code (not sure if you mention that as an exact number or  just approximate).

**Comment by shukwong** [comment]
Thanks, Brent! Yes, it's not because of jigv (1500 is just approx). I think it has to do with the default subsamling of reads in igv.js (e.g. https://github.com/igvteam/igv.js/issues/249). I am wondering if there's a way to pass some parameters to igv.js to turn off subsampling or set samplingDepth to a higher number?

**Comment by brentp** [comment]
ah. I understand now. There's not a good way to do this. That's the major limitation of the current jigv the I never fixed--it's hard to allow the user to specify simple javascript to do things like set `sampleDepth`.

If you want to modify jigv, you can use this diff:
```Patch
diff --git a/track.nim b/track.nim
index 94b8296..e9242f7 100644
--- a/track.nim
+++ b/track.nim
@@ -136,6 +136,7 @@ proc `%`*(T:Track): JsonNode =
     fields["coverageTrackHeight"] = % 24
     fields["showSoftClips"] = % true
     fields["viewAsPairs"] = % true
+    fields["samplingDepth"] = % 2000
   return JsonNode(kind: JObject, fields: fields)
 
 proc `$`*(T:Track): string =
```
and re-build. I'll have a look at making this easier with user-specified javascript from the command-line, but I don't see a simple way right now.

**Comment by shukwong** [comment]
Great! That's exactly what I was looking for! I will give it a try, thank you so much!
