### ISSUE TITLE
vcf sites html does not show alignments

### ISSUE THREAD

**Issue by mhanbioinfo** [brentp/jigv#23]
thank-you for a really great tool. I just have one issue - when I use .vcf to define sites, the .html output does not show any alignments in the alignments track, instead I just get a bar at the nucleotide with the mutation, and when I click on the bar it displays the VCF information. I do get the reads and alignments when I use .bed to define the sites.

**Comment by brentp** [comment]
can you show the full command that you ran?

**Comment by mhanbioinfo** [comment]
Hi Brent, please see my full command:
${SRC_DIR}/jigv \
    --sites ${VCF_F} \
    --fasta ${FASTA} \
    --annotation ${REF_ANNOT} \
    --flank=100 \
    ${FILE} > ${OUT_DIR}/${SAMPLE_NAME}.html

I did not get any error messages, here is the output to stderr/out:
locus:chr2:178587966-178588167
locus:chr2:178789545-178789746
locus:chr7:100969573-100969774
locus:chr7:152235711-152235912
locus:chr8:144514035-144514236
locus:chr8:144515682-144515883
locus:chr9:136502283-136502484
locus:chr12:11885887-11886095
locus:chr16:3745027-3745228
locus:chr17:80195350-80195551
locus:chr19:1619820-1620021
locus:chr19:8936338-8936539
locus:chr19:8936339-8936540
[jigv] writing 13 regions to html

I've attached a screenshot of the .html output as well.
![Screenshot 2023-05-12 at 1 10 52 PM](https://github.com/brentp/jigv/assets/98410560/8439b2ce-d180-4c55-8065-a68e3df43b09)

I'm wondering if it's an issue with my VCF, it is a single sample VCF, indexed, with valid header and VEP annotated. I tried no VEP annotation VCF as well but still did not work.

Thanks again for your time.

**Comment by brentp** [comment]
I'll look into this. Can you verify that you are using the latest release of jigv and report any error messages from the javascript error console? (you can see these with ctrl+shift+j in chrome)
(Or if you can share the html, that would help me debug).

**Comment by mhanbioinfo** [comment]
Hi Brent, I'm still using 0.1.8, will try v0.1.10. I emailed you the .html file. The error I see is a warning about no index found, and another "DevTools failed to load source map:..." error. Sorry I'm not familiar with javascript, hope the .html file helps. Please let me know if there's anything else you need. Thanks again.
