### ISSUE TITLE
Security: users with access to the same server can see each others sessions

### ISSUE THREAD

**Issue by hdashnow** [brentp/jigv#8]
For example if I do:
`ssh -N -L localhost:5001:localhost:5001 sharedserver` then browse to `http://localhost:5001/` I can see another user's jigv session. Suggest adding a password or something similar so that only the originating user and those they give access to can see their session.

**Comment by sbamin** [comment]
Agree and nice to have a minimal security. One option is to enable jwt or OAuth2 based login, https://github.com/tarent/loginsrv though I doubt if it needs be embedded in jigv.  

I have now GO-based multiple servers ([igv-webapp](https://github.com/igvteam/igv-webapp), webdav, REST services) bound to localhost (relatively secure access) and then expose those to work network via OAuth2 login using Caddy v1 (deprecated) port of https://github.com/tarent/loginsrv

**Comment by brentp** [comment]
This is no longer an issue now that there is no server.
